<!DOCTYPE html>
<html lang="pt-br" dir="ltr" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset=UTF-8>
    <meta name="viewport" content="width=device-width">
    <link rel="icon" href="../img/logo.jpg" type="image/x-icon">
    <?php $titulo = 'Dashboard' ?>
    <title><?php echo $titulo ?></title>

    <!-- CSS do site -->
    <link rel="stylesheet" href="../css/titulo-super-promocao.css">
    <link rel="stylesheet" href="../css/reponsivo.css">
    <link rel="stylesheet" href="../css/header.css">
    <link rel="stylesheet" href="../css/card-produtos.css">
    <link rel="stylesheet" href="../css/card-cadastro.css">
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="../css/carrossel.css">
    <link rel="stylesheet" href="../css/produtos-destaques.css">
    <link rel="stylesheet" href="../css/newsletters.css">
    <link rel="stylesheet" href="../css/tudo-sobre-moda.css">
    <link rel="stylesheet" href="../css/super-destaque.css">
    <link rel="stylesheet" href="../css/botoes.css">


    <!-- Fontes externas -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet"
          href="https://fonts.sandbox.google.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Script boostrap script -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossOrigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossOrigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossOrigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

</head>
<body>

<header>
    <section class="header-section">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="div-logo">
                <a class="navbar-brand" href="/home">
                    <img src="../img/logo.jpg" alt="lgo" width="60"
                         style="border-radius: 50px" height="60"></a>
            </div>
            <button class="navbar-toggler burger-principal" type="button" data-toggle="collapse"
                    data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="divi-header">
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="/dashboard-administrativo"><span
                                        class="material-icons-outlined">home</span></a>
                        </li>
                        <li><a href="/logar">Login</a></li>
                        <li><a href="/cadastrar-produtos">Cadastre-se</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="divi-header">
            <form method="" enctype="multipart/form-data" class="header-input">
                <input name="pesquisa" id="pesquisa" type="search" placeholder="pesquisar">
                <div class="pesquisa-avancada">
                    <select class="form-select form-select-sm" name="categoria" aria-label=".form-select-sm example">
                        <option selected>categorias</option>
                        <option value="acessorio">Acessório</option>
                        <option value="bicicleta">Bicicleta</option>
                        <option value="celulares">celulares</option>
                        <option value="eletronicos">eletronicos</option>
                        <option value="carinho">Carrinho</option>
                        <option value="cama">cama</option>
                        <option value="sofa">sofa</option>
                        <option value="quarto">quarto</option>
                        <option value="banheiro">banheiro</option>
                        <option value="cozinha">cozinha</option>
                        <option value="vestuario">vestuário</option>
                    </select>
                </div>
                <a href="#produto-scroll">
                    <button class="btn-busca">
                        <span class="material-symbols-outlined">search</span>
                    </button>
                </a>
            </form>
        </div>
    </section>
    <?php // definindo a vareavel global
    if (isset($_SESSION['msg'])) {
        echo $_SESSION['msg'];
        unset($_SESSION['msg']);
    }
    if (isset($_SESSION['msgcad'])) {
        echo $_SESSION['msgcad'];
        unset($_SESSION['msgcad']);
    }
    ?>
</header>
