<section class="section-brinquedos">
    <section class="mini-menu">
        <ul class="ul-mini-menu">
            <a class="link-busca-sub" href="busco-sub">
                <li class="li-mini-menu">Menina</li>
            </a>
            <a class="link-busca-sub" href="busco-sub">
                <li class="li-mini-menu">Menino</li>
            </a>
            <a class="link-busca-sub" href="busco-sub">
                <li class="li-mini-menu">Bonecas</li>
            </a>
            <a class="link-busca-sub" href="busco-sub">
                <li class="li-mini-menu">Carrinhos</li>
            </a>
            <a class="link-busca-sub" href="busco-sub">
                <li class="li-mini-menu">Heróis</li>
            </a>
            <a class="link-busca-sub" href="busco-sub">
                <li class="li-mini-menu">Princesas</li>
            </a>
        </ul>
    </section>
    <section class="section-card-sub">

    </section>
</section>

<style>
    .link-busca-sub {
        text-decoration: none;
        color: inherit;
    }

    .section-brinquedos {
        display: flex;
        flex-wrap: wrap;
        flex-direction: row;
        margin: auto;
        width: 65%;

        margin-top: 3rem;
        height: auto;
        justify-content: flex-end;
    }

    .mini-menu {
        display: flex;
        flex-direction: row;
    }

    .li-mini-menu {
        margin-left: 30px;

        cursor: pointer;
        transition: 0.5s;
        padding: 2px 20px;
        border-radius: 15px;

        box-shadow: 0px 10px 20px rgba(31, 31, 31, 0.18);
        color: white;
        background: #EED9A3;

        border: 1px solid rgba(155, 155, 155, 0.25);
    }

   .li-mini-menu:hover {
        transition: 0.8s;
        color: #444444;
        border: 1px solid rgba(58, 58, 58, 0.2);

        border-radius: 2px;
    }

</style>