<section class="section-botao-topo">
    <a href="#" class="link-botao">^</a>
</section>

<style>
    .link-botao{
        position: relative;
        margin-top: 0;
        color: white;
        font-size: 1rem;
        text-decoration: none;
        padding: 1rem;
        float: right;
        background: #444444;
        z-index: 1500;
        border: 1px solid rgba(255, 255, 255, 0.45);
        box-shadow: 10px 10px 15px rgb(0 0 0 / 14%);
    }
</style>