<?php session_start() ?>
<?php $erro = isset($_GET["erro"]) ? $_GET["erro"] : 0;  // retorna erro se houver algum na url
?>
<?php
// alto reload refrex

$page = $_SERVER['PHP_SELF'];
$sec = "15";
?>

<meta http-equiv="refresh" content="<?php echo $sec?>;URL='<?php echo $page?>'">
<meta name="viewport" content="width=device-width">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="stylesheet" href="../css/login-adm.css">
<link rel="stylesheet" href="../css/reponsivo.css">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<section class="section-login">
    <section class="cadastro-login">
        <form action="/realizar-login" method="post" class="formularioLogin">
        <?php // definindo a vareavel global
        if (isset($_SESSION['msg'])) {
            echo $_SESSION['msg'];
            unset($_SESSION['msg']);
        }
        if (isset($_SESSION['msgcad'])) {
            echo $_SESSION['msgcad'];
            unset($_SESSION['msgcad']);
        }
        ?>
        <h2 class="login-h2">Loja Ecommerce Dígital</h2>
            <label for="email" class="label-login">Usuário</label>
                <input type="text" class="input-login" name="usuario" placeholder="Insira o usuário">
            <label for="senha" class="label-login">Senha </label>
                <input type="password" class="input-login" name="senha" placeholder="digite sua senha">
            <input type="submit" value="Entrar" class="button-login" name="btnLogin">
        <a href="/dashboard" class="icon-login"><span class="material-icons">home</span></a>
        </form>
    </section>
</section>


