<?php session_start() ?>
<?php $erro = isset($_GET["erro"]) ? $_GET["erro"] : 0;  // retorna erro se houver algum na url
?>
<?php
// alto reload refrex

$page = $_SERVER['PHP_SELF'];
$sec = "15";
?>

<meta http-equiv="refresh" content="<?php echo $sec?>;URL='<?php echo $page?>'">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<section class="section-login">
    <section class="cadastro-login">
        <form action="/realizar-login" method="post" class="formularioLogin">
        <?php // definindo a vareavel global
        if (isset($_SESSION['msg'])) {
            echo $_SESSION['msg'];
            unset($_SESSION['msg']);
        }
        if (isset($_SESSION['msgcad'])) {
            echo $_SESSION['msgcad'];
            unset($_SESSION['msgcad']);
        }
        ?>
        <h2 class="login-h2">Loja Ecommerce Dígital</h2>
            <label for="email" class="label-login">Usuário</label>
                <input type="text" class="input-login" name="usuario" placeholder="Insira o usuário">
            <label for="senha" class="label-login">Senha </label>
                <input type="password" class="input-login" name="senha" placeholder="digite sua senha">
            <input type="submit" value="Entrar" class="button-login" name="btnLogin">
        <a href="/dashboard" class="icon-login"><span class="material-icons">home</span></a>
        </form>
    </section>
</section>

<style>

    .cadastro-login{
        width: 350px;
        height: 400px;
        display: flex;
        margin: auto;
        margin-top: 10rem;
        background: #EED9A3;

        border-radius: 20px;
        padding: 0 20px;
    }

    .formularioLogin {
        display: flex;
        flex-direction: column;

        margin: auto;
        text-align: center;
        width: 90%;
        font-family: 'Roboto'

    }

    .input-login {
        padding: 10px;
        margin-bottom: 10px;

        border: none;
        border-radius: 5px;
        box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.17);
    }
    .button-login {
        padding: 15px;
        border: none;
        color: white;
        background: #363636;
        border-radius: 5px;
        box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.17);
        font-family: 'Roboto', sans-serif;
        font-size: 18px;
    }
    .button-login:hover {
        border: 1px solid rgba(0, 0, 0, 0.41);
        background: white;
        color: #444444;

        border: none;

        box-shadow: none;
    }

    .label-login {
        color: #444444;
        font-family: 'Roboto', sans-serif;

    }
    .login-h2 {
        width: auto;
        transition: 0.5s ;
        font-family: 'Roboto', sans-serif;

        color: white;

        font-size: 1.1rem;

        text-align: center;
        text-transform: uppercase;
        text-shadow: 1px 5px 10px black;

        cursor: pointer;
    }
    .login-h2:hover, .icon-login:hover{
        cursor: pointer;

        transition: 1s ;
        text-shadow: 5px 5px 0px rgb(238, 217, 163);
    }
    .icon-login {
        text-decoration: inherit;
        margin: auto;
        margin-top: 2rem;
        transition: 0.5s;
        display: flex;
        justify-content: center;
        color: white;

        cursor: pointer;
        text-shadow: 0px 15px 20px rgba(0, 0, 0, 0.34);

        width: 15px;
    }

</style>

