<section class="section-menu">
    <div class="menu-lateral">
        <div class="categoria-h3">Categorias</div>
            <hr style="margin: 0">
        <ul class="opcao">
            <li class="opcao-li"><a href="/brinquedos">brinquedos</a></li>
            <hr style="margin: 0">
            <li class="opcao-li"><a href="/vestuario">vestuário</a></li>
            <hr style="margin: 0">
            <li class="opcao-li"><a href="/ferramentas">ferramentas</a></li>
            <hr style="margin: 0">
            <li class="opcao-li"><a href="/moveis">móveis</a></li>
            <hr style="margin: 0">
            <li class="opcao-li"><a href="/alimentacao">alimentação</a></li>
            <hr style="margin: 0">
        </ul>
    </div>
</section>

<style>
    .section-menu {
        display: flex;
        float: left;
        text-transform: uppercase;
    }

    .menu-lateral {
        display: block;
        justify-items: center;
        width: 250px;
        height: 500px;

        box-shadow: 5px 10px 30px rgba(0, 0, 0, 0.45);

        background: white;

        margin-top: 1rem;
        margin-left: 1.5rem;
    }

    .categoria-h3, .opcao {
        color: #444;

    }

    hr {
        border: 0;
        height: 1px;
        color: burlywood;
        background-image: -webkit-linear-gradient(left, transparent, #DBDBDB, transparent);
        background-image: linear-gradient(to right, transparent, burlywood, transparent);
        margin: 22px 0;
    }

    .categoria-h3 {
        font-weight: 300;
        margin: auto;
        margin-bottom: 0.75rem;
        margin-top: 2rem;

        text-align: center;
        width: fit-content;
    }

    .opcao {
        display: flex;
        flex-direction: column;
        justify-content: center;
    }

    .opcao-li {
        margin: auto;
        margin-top: 15px;
        margin-bottom: 5px;
    }

    ul.opcao {
        padding: inherit;
        margin: auto;
        margin: 0 50px;
        margin-top: 2rem;
    }


</style>
