<?php
//Verificar a pagina anterior e posterior
$pagina_anterior = $pagina - 1;
$pagina_posterior = $pagina + 1;
?>
</section>
<div >
    <ul class="pagination">
        <li>
            <?php
            if ($pagina_anterior != 0) { ?>
                <a href="/dashboard<?php echo $pagina_anterior; ?>" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            <?php } else { ?>
                <span aria-hidden="true">&laquo;</span>
            <?php }  ?>
        </li>
        <?php
        //Apresentar a paginacao
        for ($i = 1; $i < $num_pagina + 1; $i++) { ?>
            <li><a href="/dashboard?pagina=<?php echo $i; ?>"><?php echo $i; ?></a></li>
        <?php } ?>
        <li>
            <?php
            if ($pagina_posterior <= $num_pagina) { ?>
                <a href="/dashboard?pagina=<?php echo $pagina_posterior; ?>" aria-label="Previous">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            <?php } else { ?>
                <span aria-hidden="true">&raquo;</span>
            <?php }  ?>
        </li>
    </ul>
</div>
</div>

