
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


<section class="principal">
    <h2 class="titulo-principal">Cadastrar novo administrador</h2>
</section>

<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-inicio" role="tabpanel" aria-labelledby="nav-inicio-tab">
        <section class="principal">
            <div class="cadastrar-formulario">
                <div class="div-cadastra">
                    <section class="section-cadastrar">
                        <form action="/realiza-cadastro-administrador" method="POST" enctype="multipart/form-data">
                            <div class="cad-card">
                                <div class="cadastro-um" id="cadastro-um">
                                    <div class="div-nome">
                                        <label for="nome" class="div-label">nome</label>
                                        <input type="text" name="nome" class="nome-cad"
                                               placeholder="digite seu nome" required>
                                    </div>
                                    <div class="div-nome">
                                        <label for="nome" class="div-label">Usuário</label>
                                        <input type="text" name="usuario" class="nome-cad"
                                               placeholder="Usuário do sistema" required>
                                    </div>
                                </div>
                            </div>
                    </section>
                </div>
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">

                        <button class="button-cadastro" id="nav-preco-tab" data-bs-toggle="tab"
                                data-bs-target="#nav-preco"
                                type="button" role="tab" aria-controls="nav-preco" aria-selected="false">PRÓXIMO
                        </button>

                    </div>
                </nav>

            </div>
        </section>
        <div class="progress barra-progresso">
            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                 style="width: 10%;" aria-valuenow="25" aria-valuemin="0"
                 aria-valuemax="100">Inicie o cadastro!
            </div>
        </div>
    </div>

    <div class="tab-pane fade" id="nav-preco" role="tabpanel" aria-labelledby="nav-preco-tab">
        <section class="principal">
            <div class="cadastrar-formulario">
                <section class="section-cadastrar">
                    <div class="div-nome">
                        <label class="div-label" for="preco">Email</label>
                        <input type="email" name="email" class="nome-cad" placeholder="seuemail@gmail.com" required>
                    </div>
                    <div class="div-nome">
                        <label class="div-label" for="preco">Senha</label>
                        <input type="password" name="senha" class="nome-cad" placeholder="*******" required>
                    </div>
                </section>
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">

                        <button class="button-cadastro" >Concluir
                        </button>

                    </div>
                </nav>
            </div>
        </section>
        <div class="progress barra-progresso">
            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                 style="width: 40%;" aria-valuenow="25" aria-valuemin="0"
                 aria-valuemax="100">80
            </div>
        </div>
    </div>

    </form>
    </section>
</div>
</div>

<style>
    .titulo-principal {
        margin: inherit;
        text-transform: uppercase;

        font-family: 'Roboto', sans-serif;
        color: #444444;
        margin-bottom: -80px;
        margin-top: -20px;

    }

    .principal {
        margin: auto;
        margin-top: 3.75rem;
        display: flex;

        flex-wrap: wrap;
        flex-direction: column;
        align-content: center;
    }


    .section-cadastrar {
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;

        font-family: 'Roboto', sans-serif;
    }

    .voltar {
        color: #444444;
    }

    .cadastrar-formulario {
        overflow: hidden;
        margin-top: 4.75rem;
        display: flex;
        flex-direction: column;
        justify-content: space-around;
        padding: 20px;
        box-shadow: 5px 10px 15px rgba(0, 0, 0, 0.25);
        border: none;

        border-radius: 12px;
        width: 400px;
        height: 554px !important;
    }

    .cad-card {
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 15px;

    }


    .div-cadastra {
        display: flex;
        flex-direction: column;
    }

    .nome-cad, .button-cadastro {
        display: flex;
        justify-items: center;

    }

    .nome-cad {
        border: 0.5px solid rgba(0, 0, 0, 0.25);
        padding: 5px;
        border-radius: 5px;
    }

    .button-cadastro {
        display: inline;
        justify-items: center;
        padding: 15px;
        background: bisque;
        border: none;
        margin: auto;

        width: 85%;

        text-align: center;
        text-transform: uppercase;
        font-size: 18px;
        font-family: 'Roboto', sans-serif;
        color: white;

        border-radius: 12px;
        box-shadow: 5px 10px 15px rgba(0, 0, 0, 0.25);
    }

    .button-cadastro:hover {
        background: #363636;
    }

    .nav-tabs {
        justify-content: center;
        border: none !important;
    }

    input, textarea, select {

        font-size: 14px;

        text-transform: capitalize;
        margin-top: 15px !important;
        padding: 15px !important;

        border: none !important;
        background: #FFFFFF;
        box-shadow: 0px 4px 19px rgba(0, 0, 0, 0.1);
        border-radius: 20px;

    }

    textarea {
        padding: 15px !important;
        height: 190px !important;
    }

    .selecione-foto {
        display: flex;
        justify-content: center;

        font-family: 'Roboto', sans-serif;

        border-radius: 5px;
        background: #FFFFFF;
        width: 200px;
        text-align: center;
        margin: auto;

        padding: 3px;

        box-shadow: 0px 4px 19px rgba(0, 0, 0, 0.1);

        margin-bottom: 35px;
    }

    .div-imagem {
        height: 236px !important;
        border: 2px dashed #6c757d !important;
        width: 70%;
        margin: auto;
        margin-bottom: 25px;
        object-fit: scale-down !important;
    }

    .imagem-cadastro {
        justify-content: inherit !important;
    }

    input[type="file"] {
        display: none;
    }

    .imagem {
        display: flex;
        justify-content: center;
        margin: auto;
        height: 100% !important;
        flex-direction: column;
        align-items: center;

        opacity: 0.8;
        cursor: pointer;
    }

    .imagem:hover {
        opacity: 1;
        color: #EED9A3;
    }

    .div-nome {
        display: flex;
        flex-direction: column;

        margin-bottom: 25px;

        text-transform: capitalize;

        font-weight: 700;

        font-size: 24px;
        color: #6a6a6a;

        text-align: center;
    }

    .barra-progresso {
        margin: auto;
        margin-top: 25px;

        width: 80%;
    }

    .completo {
        margin-top: 25px;
        margin-bottom: 5px !important;
    }

</style>
