<section class="card-section">
    <div class="titulo-lista-produto">
        <h1>Confira nossa lista de produtos</h1>
    </div>
    <?php include_once __DIR__.'./../../../view/listar-produtos.php'?>
</section>

<style>

    .titulo-lista-produto {
        display: flex;
        flex-direction: row;
        width: 100%;
        font-size: 40px;
        text-align: center;
        margin: auto;
        justify-content: center;
        margin: 200px 0;

        color: rgba(157, 157, 157, 0.64);
        object-fit: scale-down !important;

        text-transform: uppercase;

    }
    .span-desconto {
        opacity: 1;
        background: #e58d04;
        padding: 4px;
        margin-bottom: -65px;
        margin-right: 10px;
        float: right;

        font-size: 10px;

        font-weight: 400;

        color: white;

        border-radius: 0 0 3px 3px;

        z-index: 150;

        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.24);

        display: flex;
        flex-direction: column;
        text-align: center;

        position: relative;
    }
    .span-descricao{
        opacity: 0;
        margin: 0;
        height: 0;

        transition: 0.3s;
    }

    .span-descricao:hover {
        height: auto;

        transition: 0.8s;
        opacity: 1;

        color: white;

        font-size: small;

        background: rgb(229, 141, 4);

        border-radius: 5px;

        padding: 8px;

        margin-top: 10px;

        z-index: 200;

    }
    .descricao {
        color: rgb(54, 54, 54);

    }
    .card-section {
        display: flex;
        flex-wrap: wrap;
        flex-direction: row;
        margin: auto;
        width: 70%;
        height: auto;
        justify-content: center;
    }

    .cards {
        display: flex;
        flex-direction: column;
        padding-left: 3rem;
        align-items: center;

        margin-bottom: 35px;
        height: 350px;
    }

    .imagem-produto {
        width: 220px;
        height: 199px;

        box-shadow: -10px 7px 16px 0px rgb(0 0 0 / 25%);
        object-fit: scale-down !important;

    }

    .titulo-produto {
        margin: auto;
        margin-top: 15px;
        color: #444;
        font-size: 18px;
        font-family: 'Roboto', sans-serif;

        font-weight: 500;
    }

    .preco, .valor {

        font-family: 'Roboto', sans-serif;
        margin: auto;
        width: auto;
        display: flex;
    }

    .preco {
        color: #000;
        margin-top: 10px;
        margin-bottom: -10px;
        font-size: 15px;
    }

    .valor {
        color: #6a6a6a;
    }

    .button-produto {
        width: 146px !important;
        height: 29px !important;

        border-radius: 12px !important;

        margin-top: 20px;

        color: white !important;
        background: #6a6a6a !important;

        font-size: 18px;
        font-family: 'Roboto', sans-serif;
        text-transform: uppercase;

        border: none;
    }

    .button-produto:hover {
        transition: 0.8s;
        background: bisque !important;
    }

    .link-compra {
        color: inherit;
        text-decoration: inherit;
    }
    .codigo {
        color: #6a6a6a;
        font-size: 8px;
    }
</style>