<section class="card-section">
    <?php include_once __DIR__.'./../../../view/listar-produtos.php'?>
</section>

<style>
    .card-section {
        display: flex;
        flex-wrap: wrap;
        flex-direction: row;
        margin: auto;
        width: 75%;

        margin-top: 1rem;
        height: auto;
    }

    .card {
        display: flex;
        flex-direction: column;
        padding-left: 3rem;
        align-items: center;

        margin-bottom: 35px;

        width: 202px;
        height: 323px;
    }

    .imagem-produto {
        width: 202px;
        height: 199px;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;

        box-shadow: 0 3px 10px rgba(0, 0, 0, 0.25);
    }

    .titulo-produto {
        margin: auto;
        margin-top: 15px;
        color: #444;
        font-size: 18px;
        font-family: 'Roboto', sans-serif;

        font-weight: 500;
    }

    .preco, .valor {

        font-family: 'Roboto', sans-serif;
        margin: auto;
        width: auto;
        display: flex;
    }

    .preco {
        color: #000;
        margin-top: 10px;
        margin-bottom: -10px;
        font-size: 15px;
    }

    .valor {
        color: #6a6a6a;
    }

    .button-produto {
        width: 146px !important;
        height: 29px !important;

        border-radius: 12px !important;

        margin-top: 20px;

        color: white !important;
        background: #6a6a6a !important;

        font-size: 18px;
        font-family: 'Roboto', sans-serif;
        text-transform: uppercase;

        border: none;
    }

    .button-produto:hover {
        transition: 0.8s;
        background: bisque !important;
    }

    .link-compra {
        color: inherit;
        text-decoration: inherit;
    }
    .codigo {
        color: #6a6a6a;
        font-size: 8px;
    }
</style>