<section class="card-section">
    <div class="card">
        <img class="imagem-produto" src="../../../img/images.jpg" alt="carrinho">
        <h2 class="titulo-produto">CARRINHO AUTO 2.0</h2>
        <div class="preco">Preço $
            <div class="valor">259,59</div>
        </div>
        <a class="link-compra" href="/loja-compra.php">
            <button class="button-produto">
                Comprar
            </button>
        </a>
    </div>
    <div class="card">
        <img class="imagem-produto" src="../../../img/images.jpg" alt="carrinho">
        <h2 class="titulo-produto">CARRINHO AUTO 2.0</h2>
        <div class="preco">Preço $
            <div class="valor">259,59</div>
        </div>
        <a class="link-compra" href="/loja-compra.php">
            <button class="button-produto">
                Comprar
            </button>
        </a>
    </div>
    <div class="card">
        <img class="imagem-produto" src="../../../img/images.jpg" alt="carrinho">
        <h2 class="titulo-produto">CARRINHO AUTO 2.0</h2>
        <div class="preco">Preço $
            <div class="valor">259,59</div>
        </div>
        <a class="link-compra" href="/loja-compra.php">
            <button class="button-produto">
                Comprar
            </button>
        </a>
    </div>
    <div class="card">
        <img class="imagem-produto" src="../../../img/images.jpg" alt="carrinho">
        <h2 class="titulo-produto">CARRINHO AUTO 2.0</h2>
        <div class="preco">Preço $
            <div class="valor">259,59</div>
        </div>
        <a class="link-compra" href="/loja-compra.php">
            <button class="button-produto">
                Comprar
            </button>
        </a>
    </div>
</section>

<style>
    .card-section {
        display: flex;
        flex-wrap: wrap;
        flex-direction: row;
        margin: auto;
        width: 75%;

        margin-top: 1rem;
        height: 70vh;
    }

    .card {
        display: flex;
        flex-direction: column;
        padding-left: 3rem;
        align-items: center;

        width: 202px;
        height: 323px;
    }

    .imagem-produto {
        width: 202px;
        height: 199px;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;

        box-shadow: 0 3px 10px rgba(0, 0, 0, 0.25);
    }

    .titulo-produto {
        margin: auto;

        color: #444;
        font-size: 18px;
        font-family: 'Roboto', sans-serif;

        font-weight: 500;
    }

    .preco, .valor {
        font-family: 'Roboto', sans-serif;
        margin: auto;
        width: auto;
        display: flex;
    }

    .preco {
        color: #000;
    }

    .valor {
        color: #6a6a6a;
    }

    .button-produto {
        width: 146px !important;
        height: 29px !important;

        border-radius: 12px !important;

        margin-top: 10px;

        color: white !important;
        background: #6a6a6a !important;

        font-size: 18px;
        font-family: 'Roboto', sans-serif;
        text-transform: uppercase;

        border: none;
    }

    .button-produto:hover {
        transition: 0.8s;
        background: bisque !important;
    }

    .link-compra {
        color: inherit;
        text-decoration: inherit;
    }

</style>