<?php use src\doctrine\Entity\Produtos;
use src\doctrine\infra\EntityManegeFactory;

require_once __DIR__ . './../header/header-adm.phtml'; ?>
<section class="lista-produtos">
    <h1 class="h1-titulos"><?php echo $titulo ?></h1>
    <div class="lista">
        <table class="table">
            <div class="btn-pesquisa">
                <a href="/cadastrar-produtos">
                    <button class="btn-editar btn-mais">novo produto +</button>
                </a>
                <div class="header-div">
                    <form method="GET" class="header-input">
                        <input name="pesquisa" id="pesquisa" type="search" placeholder="pesquisar">
                        <div class="pesquisa-avancada">
                            <select class="form-select form-select-sm" aria-label=".form-select-sm example">
                                <option selected>categorias</option>
                                <option value="acessorio">Acessório</option>
                                <option value="bicicleta">Bicicleta</option>
                                <option value="celulares">celulares</option>
                                <option value="eletronicos">eletronicos</option>
                                <option value="carinho">Carrinho</option>
                                <option value="cama">cama</option>
                                <option value="sofa">sofa</option>
                                <option value="quarto">quarto</option>
                                <option value="banheiro">banheiro</option>
                                <option value="cozinha">cozinha</option>
                                <option value="vestuario">vestuário</option>
                            </select>
                        </div>
                        <button class="button-header"><span class="material-icons">search</span></button>
                    </form>
                </div>

            </div>
            <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">nome</th>
                <th scope="col">descrição</th>
                <th scope="col">preço</th>
                <th scope="col">Categoria</th>
            </tr>
            </thead>
            <tbody>
            <?php

            $entityManegerFactory = new EntityManegeFactory();
            $entityManeger = $entityManegerFactory->getEntityManege();


            $valor_a_buscar = filter_input(
                INPUT_GET,
                'pesquisa',
                FILTER_SANITIZE_STRING
            );

            $result_produtos = "SELECT * FROM `produtos`
            WHERE 'nome' LIKE '%$valor_a_buscar%'
            OR 'categoria' LIKE '%$valor_a_buscar%'
            OR 'subcategoria' LIKE '%$valor_a_buscar%'
            OR 'marcas' LIKE '%$valor_a_buscar%'
            OR 'preco' LIKE '%$valor_a_buscar%'
            OR 'decricao' LIKE '%$valor_a_buscar%'
            OR 'desconto' LIKE '%$valor_a_buscar%'
            OR 'titulo_produto' LIKE '%$valor_a_buscar%'";;




            // Buscando o repositorio de alunos pelo Entity
            $produtosRepository = $entityManeger->getRepository(Produtos::class);


            /** @var Produtos[] $alunos */
            $produtos = $produtosRepository->findAll();

            foreach ($produtos as $produto):?>
                <tr>
                    <th scope="row"><?= $produto->getId() ?></th>
                    <td><?= $produto->getNome() ?></td>
                    <td><?= $produto->getDescricao() ?></td>
                    <td>R$<?= $produto->getPreco() ?></td>
                    <td><?= $produto->getCategoria() ?></td>
                    <div class="btn-ed-exc">
                        <td><a href="/exluir-produtos?id=<?= $produto->getId() ?>">
                                <button class="btn-editar">Editar</button>
                            </a></td>
                        <td><a href="/editar-produtos?id=<?= $produto->getId() ?>">
                                <button class="btn-excluir">Excluir</button>
                            </a></td>
                    </div>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</section>


<style>
    body{ background: #FFFFFF}
    .header-div {
        display: flex;
        flex-direction: row;
        justify-content: end;
    }

    .header-div input {
        border-radius: 12px 0 0 12px;
        border: 1px solid rgba(126, 126, 126, 0.48);
        padding: 0 15px;
    }

    .header-div button {
        background: #444444;
        color: #FFFFFF;
        border: none;
        border-radius: 0 12px 12px 0;
    }

    .material-icons {
        padding: 0;
    }

    .btn-pesquisa {
        display: flex;
        justify-content: space-between;
    }

    .header-div select {
        padding: 5px 15px;
        border-radius: inherit;
    }

    .h1-titulos {
        text-align: center;
        margin: 2rem 0;
    }

    .lista {
        width: 80%;
        margin: auto;
        margin-top: 3rem;
    }

    .btn-ed-exc {
        width: 250px !important;
    }

    .btn-editar, .btn-excluir {
        border-radius: 12px;
        border: none;
        font-weight: bold;
        color: #FFFFFF;
        padding: 3px 25px;
        text-transform: uppercase;
    }

    .btn-editar {
        background: #999;
    }

    .btn-excluir {
        background: #444444;
    }

    .btn-mais {
        font-size: 12px;
        padding: 6px 15px;
    }

    td {
        font-size: 12px;
    }
</style>