<section class="contato-newsletter">
    <?php // definindo a vareavel global
    if (isset($_SESSION['msg'])) {
        echo $_SESSION['msg'];
        unset($_SESSION['msg']);
    }
    if (isset($_SESSION['msgcad'])) {
        echo $_SESSION['msgcad'];
        unset($_SESSION['msgcad']);
    }
    ?>
    <form method="post" action="/salvar-newsletters" class="footer-contato-newsletters" enctype="multipart/form-data">
        <h2 class="footer-sub-contato-news">receber newsletter</h2>
        <div class="input-enviar">
            <input type="email" class="input-newsletter" name="newsletter" placeholder="Digíte seu email aqui">
            <button class="newsletter-btn">Enviar</button>
        </div>
    </form>
</section>

<style>

    .input-enviar {
        display: flex;
        flex-direction: row;
        justify-content: center;
    }

    .contato-newsletter {
        width: 100%;
        display: flex;
        justify-content: center;
        height: 300px;

        background: #444444;

        margin: 5rem 0;
    }

    .newsletter-btn {
        transition: 0.5s;
        background: #EED9A3;
        color: white;
        font-weight: 700;
        height: 40px;
        border: none;
        border-radius: 0 12px 12px 0;
        box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.26);
        padding: 7px;
        padding: 0 1.7rem;
        margin-left: -5px;
    }

    .newsletter-btn:hover {
        transition: 0.8s;
        border-radius: 3px;
        color: rgb(68, 68, 68);
        background: #ffffff;
    }

    .input-newsletter {
        width: 60% !important;
        padding: 20px;

        border: none;
        height: 40px;

        background: #FFFFFF;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
        border-radius: 12px 0 0 12px;
    }

    .footer-contato-newsletters {
        margin: auto;
        text-align: center;
        width: 50%;
        padding: 52px 15px;
    }

    .footer-sub-contato-news {
        color: #FFFFFF;
        font-weight: 700;
        font-size: 35px;
        text-transform: uppercase;
        margin-bottom: 25px;
    }

    /*** parte responsiva ***/
    @media screen and (max-width: 500px) {
        .footer-contato-newsletters {
            text-align: center;
            padding: 52px 15px;
            width: inherit;
        }
        .footer-sub-contato-news{
            font-size: 24px;
        }
    }

</style>