<?php

use src\doctrine\infra\MysqlConnect;

session_start();

$mysql = (new MysqlConnect())->conect();
?>
<body>
<?php
// Definimos o nome do arquivo que será exportado
$arquivo = 'relatorioProdutos.xls';

// Criamos uma tabela HTML com o formato da planilha
$html = '';
$html .= '<table border="1" font-family: Arial, Helvetica, sans-serif;>';
$html .= '<tr>';
$html .= '<td colspan="19"><b><h2  style="text-align: center; font-family: Arial, Helvetica, sans-serif; text-transform: uppercase;">Planilha Informacoes dos Cadastros</h2></b></td>';
$html .= '</tr>';


$html .= '<tr>';
$html .= '<td><b>ID</b></td>';
$html .= '<td colspan="2"><b>Nome</b></td>';
$html .= '<td  colspan="2"><b>descrição</b></td>';
$html .= '<td colspan="2"><b>Titulo</b></td>';
$html .= '<td colspan="3"><b>Preço</b></td>';
$html .= '<td><b>Categoria</b></td>';
$html .= '<td><b>Sub Categoria</b></td>';
$html .= '<td colspan="2"><b>Destaque</b></td>';
$html .= '<td colspan="2"><b>Data de criação</b></td>';
$html .= '</tr>';

//Selecionar todos os itens da tabela
$result_msg_contatos = "SELECT * FROM produtos;";
$resultado_msg_contatos = mysqli_query($mysql, $result_msg_contatos);

while ($row_msg_contatos = mysqli_fetch_assoc($resultado_msg_contatos)) {
    $html .= '<tr>';
    $html .= '<p class="dados"><b>ID:</b> ' . $row_msg_contatos["id"] . '</p>';
    $html .= '<p class="dados"><b>Nome:</b> ' . $row_msg_contatos["nome"] . '</p>';
    $html .= '<p class="dados"><b>Descrição:</b> ' . $row_msg_contatos["descricao"] . '</p>';
    $html .= '<p class="dados"><b>Titulo: </b>' . $row_msg_contatos["titulo_produto"] . '</p>';
    $html .= '<p class="dados"><b>Preço:</b>' . $row_msg_contatos["preco"] . '</p>';
    $html .= '<p class="dados"><b>Categoria:</b> ' . $row_msg_contatos["categoria"] . '</p>';
    $html .= '<p class="dados"><b>Sub Categoria:</b>' . $row_msg_contatos["subcategoria"] . '</p>';
    $html .= '<p class="dados"><b>Destaque: </b>' . $row_msg_contatos["ehdestaque"] . '</p>';
    $data  = '<p class="dados"><b>Data de criação:</b>' . date('d/m/Y H:i:s', strtotime($row_msg_contatos["DataDeCriacao"])) . '</p>';
    $html .= $data;
    $html .= '</tr>';

}
// Configurações header para forçar o download
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");
header("Cache-Control: no-cache, must-revalidate");
header("Pragma: no-cache");
header("Content-type: application/x-msexcel");
header("Content-Disposition: attachment; filename=\"{$arquivo}\"");
header("Content-Description: PHP Generated Data");
// Envia o conteúdo do arquivo
echo $html;
exit; ?>
</body>

</html>