<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


<section class="section-campo">
    <table class="table">
        <thead class="thead">
        <tr>
            <th scope="col" style="text-align: center">DADOS DO PRODUTO</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">Nome</th>
            <td>jose</td>
        </tr>
        <tr>
            <th scope="row">Descrição</th>
            <td>Produto do jose</td>
        </tr>
        <tr>
            <th scope="row">Preço</th>
            <td>1500</td>
        </tr>
        <tr>
            <th scope="row">Titulo do produto</th>
            <td> Titulo Produto do jose</td>

        </tr>
        <tr>
            <th scope="row">Desconto</th>
            <td>15%</td>
        </tr>
        <tr>
            <th scope="row"> Categoria</th>
            <td>Brinquedo</td>

        </tr>
        <tr>
            <th scope="row"> Sub-Categoria</th>
            <td>crianca</td>

        </tr>
        <tr>
            <th scope="row"> Marca</th>
            <td>Tobies</td>

        </tr>
        <tr>
            <th scope="row">Imagem</th>
            <td>Brinquedo.jpg</td>
        </tr>
        </tbody>
    </table>
</section>

