<section class="super">
    <div class="super super-div">
        <h1 class="super super-h1">SUPER PROMOÇÕES</h1>
    </div>
</section>

<style>

    .super {
        display: flex;
        justify-content: center;
    }
    .super-div{

        color: #FFFFFF;
        margin: 7rem 0;
        width: 60%;
        text-align: center;

        background: #FAE09D;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
        border-radius: 2px 155.5px 0px;

        font-style: normal;
        font-weight: 700;
        font-size: 50px;
        line-height: 84px;
    }

    h1 {
        line-height: inherit !important;
        font-size: inherit; !important;
    }

</style>