<?php


use src\doctrine\infra\MysqlConnect;

$caminho = '../img/arquivos/';

$mysql = (new MysqlConnect())->conect();

?>

<section class="super">
    <div class="super super-div">
        <h1 class="super super-h1">SUPER PROMOÇÕES</h1>
    </div>
</section>
<section class="super card-produtos">
    <div class="card esquerda">
        <?php
        $dql = "SELECT * FROM produtos WHERE `posicao_destaque` LIKE '%esquerdo%' limit 1 ";
        $dql = mysqli_query($mysql, $dql);
        if (($dql) and ($dql->num_rows != 0)):
            while ($rows = mysqli_fetch_object($dql)) : $img = $caminho . $rows->nome;
                $id = $rows->id;
                ?>
                <h5 class="card-title desconto es-esquerdo"><?= $rows->desconto?>% DESCONTO</h5>
                <img src=" <?= $img ?>" style="width: 100%; object-fit: cover" class="card-img-top" alt="<?= $rows->nome ?>">
                <div class="card-body">
                    <p class="card-text"><?= $rows->titulo_produto ?></p>
                    <button href="#" class="btn btn-comprar btn-esquerda">COMPRAR AGORA</button>
                </div>
            <?php endwhile; endif; ?>
    </div>
    <div class="card card-meio ">
        <?php
        $dql = "SELECT * FROM produtos WHERE `posicao_destaque` LIKE '%meio%' limit 1";
        $dql = mysqli_query($mysql, $dql);
        if (($dql) and ($dql->num_rows != 0)):
        while ($rows = mysqli_fetch_object($dql)) : $img = $caminho . $rows->nome;
        $id = $rows->id;
        ?>
        <h5 class="card-title desconto"><?= $rows->desconto?>% DESCONTO</h5>
        <img src="<?= $img ?>" style="object-fit: cover; width: 100%;" class="card-img-top card-foto" alt="<?= $rows->nome ?>">
        <div class="card-body">
            <p class="card-text"><?= $rows->titulo_produto ?></p>
            <button href="#" class="btn btn-comprar">COMPRAR AGORA</button>
        </div>
        <?php endwhile; endif; ?>
    </div>
    <div class="card direita">
        <?php
        $dql = "SELECT * FROM produtos WHERE `posicao_destaque` LIKE '%direito%' limit 1 ";
        $dql = mysqli_query($mysql, $dql);
        if (($dql) and ($dql->num_rows != 0)):
            while ($rows = mysqli_fetch_object($dql)) : $img = $caminho . $rows->nome;
                $id = $rows->id;
                ?>
        <h5 class="card-title desconto des-direto"><?= $rows->desconto?>% DESCONTO</h5>
        <img src="<?= $img ?>" style=" object-fit:cover; width: 100%" class="card-img-top" alt="<?= $rows->nome ?>">
        <div class="card-body">
            <p class="card-text"><?= $rows->titulo_produto ?></p>
            <button href="#" class="btn btn-comprar btn-direito">COMPRAR AGORA</button>
        </div>
        <?php endwhile; endif; ?>
    </div>
</section>


<style>
    .desconto {
        text-align: center;
        background: transparent;
        background: #000000;
        border-radius: 25px 25px 0px 0px;

        color: white;
        padding: 10px 0;
        font-weight: 700;
        margin-bottom: 0;
    }

    .es-esquerdo {
        background: #3FCA28;
    }
    .card-meio {
        height: 400px;
    }

    .card-foto {
        object-position: center !important;
    }
    .des-direto {
        background: red;
    }

    .card-produtos {
        display: flex;
        justify-content: space-around;
    }

    .esquerda, .direita {
        height: 350px !important;
    }

    .btn-esquerda, .btn-direito {
        background: #FAE09D !important;
    }

    .card-text {
        margin-top: -7rem;
        text-align: center;
        font-family: 'Roboto', Arial;
        font-style: normal;
        font-weight: 700;
        font-size: 24px;
        line-height: 28px;
        margin-bottom: 5px;
        color: #888;
        text-shadow: 1px 5px 10px rgba(112, 112, 112, 0.47);
    }

    .btn {
        padding: inherit;
    }

    .card-body {
        padding: inherit ;
    }

    .card-img-top {
        object-position: top;
        object-fit: scale-down;
        height: 355px;
    }

    .card {
        width: 230px;
        box-sizing: border-box;
        box-shadow: -20px -6px 20px 0px rgb(0 0 0 / 25%);
        border-radius: 25px 25px 0px 0px;
        overflow: hidden;
        margin-bottom: 3.75rem;
    }

    .super {
        display: flex;
        justify-content: space-around;
        align-items: end;
        width: 60%;
        margin: auto;
        font-family: 'Roboto', Arial;
    }
    /*** parte responsiva ***/
    @media screen and (max-width: 500px){
        .super {
            flex-direction: column;
        }
    }
    .btn-comprar {
        display: flex;
        justify-content: center;
        font-family: 'Roboto', Arial;
        font-style: normal;
        font-weight: 700;
        font-size: 24px;
        line-height: 28px;
        color: white;
        background: #D00F0F;
        box-sizing: border-box;
        box-shadow: 0px 1px 7px rgba(0, 0, 0, 0.25);
        border-radius: 25px;
        margin: auto;
        padding: 0 10px !important;
    }

    .super-div {

        color: #FFFFFF;
        margin: 10rem 0;
        width: 60%;
        padding: 25px 0;
        text-align: center;

        background: #FAE09D;
        box-shadow: -20px 11px 20px 0px rgb(0 0 0 / 25%);
        border-radius: 2px 155.5px 0px;

        font-style: normal;
        font-weight: 700;
    }

    h1 {
        line-height: inherit !important;
        font-size: inherit;
    }
    .super-h1 {
        font-size: 2.5rem;
        width: auto;
    }
</style>