<section class="tudo-sobre-moda">
    <div class="tudo-sobre-modas-descricao">
            <h1>Tudo Sobre Modas</h1>
             <p>Fique por dentro das novidades do momento</p>
            <p class="p-moda">Moda Masculino & Moda Feminina</p>
    </div>
</section>

<style>
    .tudo-sobre-moda {
        width: 100%;
        display: flex;
        justify-content: center;
        height: 300px;

        background: #D4D4D4;

        margin: 10rem 0;
    }
    .tudo-sobre-modas-descricao {
        text-align: center;
        font-family: 'Roboto';
        font-style: normal;
        font-weight: 500;
        font-size: 45px;
        line-height: 75px;
        margin-top: 4rem;
        color: #6A6A6A;
    }
    .tudo-sobre-modas-descricao p {
        font-size: 24px;
        margin-top: -25px;
        font-weight: 300;
    }
    .tudo-sobre-modas-descricao .p-moda {
        font-weight: 700;
        font-weight: bolder;
        margin-top: -65px;
    }
</style>