<?php

// incluindo os arquivos
use src\doctrine\Entity\Produtos;

require_once __DIR__. './../../../vendor/autoload.php';
require_once __DIR__ . './../../Entity/Produtos.php';
require_once __DIR__ . './../EntityManegeFactory.php';

if (($_SERVER['REQUEST_METHOD']) === 'POST') {

        $cadastrar = new Produtos($mysql);
        $cadastrar->adicionarProduto(
           $nome = $_POST['nome'],
           $descricao = $_POST['descricao'],
           $preco = $_POST['preco'],
           $titulo_produto = $_POST['titulo_produto'],
           $preco_desc = $_POST['preco_desc'],
           $imagem_produto = $_FILES['imagemProduto'],
           $categoria = $_POST['categoria'],
           $subcategoria = $_POST['subcategoria'],
           $marcas = $_POST['marca']
        );
}