<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
<head>
    <meta charset=UTF-8>
    <meta name="viewport" content="width=device-width">
    <link rel="icon" href="../img/logo.jpg" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
<?php
session_start();
if ((!isset ($_SESSION['usuario']) == true) and (!isset ($_SESSION['senha']) == true) and (!isset ($_SESSION['id']) == true)) {
    unset($_SESSION['id']);
    unset($_SESSION['usuario']);
    unset($_SESSION['senha']);
    header('location: /logar');
}

?>
<header>
    <section class="container-adm">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="/home">
                <img src="../img/logo.jpg" alt="lgo" width="60"
                     style="border-radius: 50px" height="60"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/dashboard-administrativo"><span class="material-icons-outlined">home</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Cadastros
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/cadastrar-produtos">Cadastrar produtos</a>
                            <a class="dropdown-item" href="/cadastrar-novo-administrador">Cadastrar adm</a>
                            <a class="dropdown-item" href="/banner">Cadastrar banner</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Excluir
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/excluir-produto">Excluir produtos</a>
                            <a class="dropdown-item" href="/excluir-banner">Excluir banner</a>
                            <a class="dropdown-item" href="/Excluir-adm">Excluir administrador</a>
                            <a class="dropdown-item" href="/Excluir-usuario">Excluir usuario</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Edições
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/super-promocao">Editar Super promoção</a>
                            <a class="dropdown-item" href="/produtos">Editar produtos</a>
                            <a class="dropdown-item" href="/editar-usuario">Editar usuario</a>
                            <a class="dropdown-item" href="/editar-adm">Editar adm</a>
                            <a class="dropdown-item" href="/editar-banner">Editar banner</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </section>

                <div class="logado">
                    <?php
                    if (assert($_SESSION['id'])) {
                        echo " Olá, " . "<b>" . $_SESSION['usuario'] . "</b>" . "<br>";
                        echo "<br><a class='sair' href='/sair'>Sair</a>";
                    } else {
                        $_SESSION['msg'] = "Somente administradores";
                        header("Location: /logar");
                    }

                    ?>
                </div>
</header>
<style>
.navbar navbar-expand-lg navbar-light {
    background: #EED9A3 !important;
}
.navbar {
    width: 90% !important;
    margin: auto !important;
}
.container-adm {
    background: #EED9A3;
}
.navbar-expand-lg .navbar-collapse {
    justify-content: flex-end !important;
}
.logado {
    text-align: center;
    display: flex;
    justify-content: space-around;
    width: 150px;
    font-size: small;
    align-items: center;
    justify-items: center;
    margin: auto;
}

.logado a {
    text-decoration: none;
    color: #444444;
}

.logado a:hover {
    color: #FFFFFF;
}

    @media screen and (max-width: 1125px) {
        .adm > ul {
            display: flex;
            flex-direction: column;
        }

        .dropdown-item{
            display: flex;
        }

    }
</style>



