<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<section class="header-section">
    <div class="header-div"><a class="link-home" href="/home"><img src="../../../img/celular.jpg" alt="logo"></a></div>
    <div class="header-div">
        <div class="header-input">
            <input name="pesquisa" type="search" placeholder="pesquisar">
            <button class="button-header"><span class="material-icons">search</span></button>
        </div>
    </div>
    <div class="header-div">
        <ul>
            <li><a href="/"><span class="material-icons">home</span></a></li>
            <li><a href="/cadastrar-cliente.php">Cadastre-se</a></li>
            <li><a href="/logar.php"><span class="material-icons">login</span></a></li>
        </ul>
    </div>
</section>

<style>

    html,
    body {
        margin: auto;
        font-family: 'Roboto', sans-serif;
    }
    .link-home {
        text-decoration: none;
        color: inherit;
    }
    .header-section {
        position: relative;
        display: flex;
        justify-content: space-around;
        width: 100%;
        height: 100px;

        background: #EED9A3;
        color: white;
    }

     .header-div {
        display: flex;
        align-items: center;
        width: 33%;
        justify-content: center;
    }

    ul, li {
        margin: auto;
        display: flex;
    }

    li {
        margin-left: 20px;
    }

    input {
        width: 300px;
        border: none;
        padding: 5px;

        text-align: center;

        height: 40px;
        border-radius: 30px;
        background: white;

    }
    .button-header {
        color: white;

        background: burlywood !important;

        border: none;

        box-shadow: -5px 5px 20px rgba(0, 0, 0, 0.29);

        width: 15% !important;
    }

    .header-input, .button-header {
        width: 350px;
        height: 40px;
        display: flex;
        justify-content: center;
        align-items: center;

        border-radius: 30px;

        background: white;
    }

    li>a {
        text-decoration: none;
        color: inherit;
    }
    li>a:hover {
        color:burlywood;
    }
</style>