<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
<head>
    <meta charset=UTF-8>
    <meta name="viewport" content="width=device-width">
    <link rel="icon"  href="../img/logo.jpg" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<header>
    <section class="header-section">
        <div class="div-header"><a class="link-home" href="/home"><img src="../img/logo.jpg" alt="lgo" width="60"
                                                                       style="border-radius: 50px" height="60"></a>
        </div>
        <div class="div-header">
            <ul>
                <li><a class="links-menu" href="/home"><span class="material-icons">home</span></a></li>
                <li><a class="links-menu" href="/cadastrar-produtos">Cadastre-se</a></li>
                <li><a class="links-menu" href="/excluir-produto">Excluir</a></li>
                <li><a class="links-menu" href="/sair"><span class="material-icons">logout</span></a></li>
            </ul>
        </div>
    </section>
</header>
<style>

    html,
    body {
        margin: auto;
        font-family: 'Roboto', sans-serif;

    }

    .header-section {
        font-family: 'Roboto', sans-serif;
        position: relative;
        display: flex;
        justify-content: space-around;
        width: 100%;
        height: 100px;
        align-items: center;

        color: #363636;
        background-image: linear-gradient(rgb(241, 224, 182), rgb(255, 255, 255));
    }

    ul, li {
        margin: auto;
        display: flex;
    }

    li {
        margin-left: 20px;
    }


    li > a {
        text-decoration: none;
        color: inherit;
    }

    li > a:hover {
        color: burlywood;
    }

    .div-header {
        display: flex;
        width: 50%;
        justify-content: center;
    }

    .link-home {
        text-decoration: none;
        color: inherit;
    }
</style>



