<?php $titulo = 'Dashboard' ?>
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
<head>
    <meta charset=UTF-8>
    <meta name="viewport" content="width=device-width">
    <link rel="icon" href="../img/logo.jpg" type="image/x-icon">
    <title><?php echo $titulo ?></title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</head>
<body>

<header>


    <section class="header-section">
        <section class="container">
            <div class="pesquisa-menu">
                <div class="header-div">
                    <a class="link-home" href="/home">
                        <img src="../img/logo.jpg" width="60" height="60" style="border-radius: 50px" alt="logo">
                    </a>
                </div>
                <div class="header-div">
                    <form method="GET" class="header-input">
                        <input name="pesquisa" id="pesquisa" type="search" placeholder="pesquisar">
                        <div class="pesquisa-avancada">
                            <select class="form-select form-select-sm" aria-label=".form-select-sm example">
                                <option selected>por categoria</option>
                                <option value="acessorio">Acessório</option>
                                <option value="bicicleta">Bicicleta</option>
                                <option value="celulares">celulares</option>
                                <option value="eletronicos">eletronicos</option>
                                <option value="carinho">Carrinho</option>
                                <option value="cama">cama</option>
                                <option value="sofa">sofa</option>
                                <option value="quarto">quarto</option>
                                <option value="banheiro">banheiro</option>
                                <option value="cozinha">cozinha</option>
                                <option value="vestuario">vestuário</option>
                            </select>
                        </div>
                        <button class="button-header"><span class="material-icons">search</span></button>
                    </form>
                </div>
                <div class="header-div">
                    <ul class="ul-cadastre">
                        <li><a href="/home"><span class="material-icons">home</span></a></li>
                        <li><a href="/login">Login</a></li>
                        <li><a href="/cadastrar-produtos">Cadastre-se</a></li>
                    </ul>
                </div>
            </div>
            <div class="menu-section">
                <ul class="ul-submenu">
                    <li>
                        <div class="dropdown">
                            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                Categorias
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li class="dropdown-item"><a href="/vestuario">Roupas</a></li>
                                <li class="dropdown-item"><a href="/acessorios">Acessórios</a></li>
                                <li class="dropdown-item"><a href="/brinquedos">Brinquedos</a></li>
                                <li class="dropdown-item"><a href="/ferramentas">ferramentas</a></li>
                                <li class="dropdown-item"><a href="/moveis">móveis</a></li>
                                <li class="dropdown-item"><a href="/alimentacao">alimentação</a></li>
                            </ul>
                        </div>
                    </li>
                    <li><a href="#">contato</a></li>
                </ul>
            </div>
        </section>
    </section>
</header>
<style>

    html,
    body {

        margin: auto;
        font-family: 'Roboto', sans-serif;
    }

    .btn:focus {
        box-shadow: none;
    }

    .pesquisa-avancada {
        display: flex;
    }

    .pesquisa-menu {
        display: flex;
        margin-top: 15px;
    }

    .pesquisa-avancada > select {
        border: none !important;
        height: 40px;
        border-left: 1px solid #d0d0d0 !important;
    }

    .pesquisa-avancada > select:after {
        box-shadow: inherit;
    }

    .link-home {
        text-decoration: none;
        color: inherit;
    }

    .dropdown-item, li {
        margin-left: inherit !important;
    }

    .header-section {
        display: flex;
        justify-content: space-around;
        flex-direction: column;

        width: 100%;
        height: 190px;

        background: #FAE09D;
    / / background-image: linear-gradient(#EED9A3, rgba(255, 255, 255, 0.45));
        color: #444444;
    }

    .header-div {
        display: flex;
        align-items: center;
        width: 33%;
        justify-content: center;
        margin: auto;

    }

    .ul-cadastre {
        margin: auto;
        width: 80%;
        display: flex;
        justify-content: space-around;

    }

    .ul-submenu {
        display: flex;
        margin-left: 60px;
        width: 250px;
        justify-content: space-between;;
    }

    li {
        margin: auto;
        width: 100%;
        display: flex;
        justify-content: space-around;
    }

    input {
        width: 300px;
        border: none;
        padding: 5px;

        text-align: center;

        height: 40px;
        border-radius: 15px 0px 0px 15px;
        background: white;

    }

    .form-select {
        width: inherit !important;
    }

    .button-header {
        color: white;

        background: #FAE09D !important;

        border: none;

        box-shadow: -5px 5px 20px rgba(0, 0, 0, 0.29);

        width: 15% !important;

        margin-left: 10px;
    }

    .header-input, .button-header {
        height: 40px;
        display: flex;
        justify-content: center;
        align-items: center;

        border-radius: 30px;

        background: white;
    }

    li > a {
        text-decoration: none;
        color: inherit;
    }

    li > a:hover {
        color: burlywood;
    }

    .menu-section {
        position: relative;
        padding-top: 15px;
        font-weight: normal;
        font-family: Arial;
        display: flex;
        align-items: flex-end;
        margin-bottom: -79px;
        margin-top: 5px;
    }

</style>