<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<section class="header-section">
    <div class="div-header"><img src="#" alt="lgo"></div>
    <div class="div-header">
        <ul>
            <li><a class="links-menu" href="/"><span class="material-icons">home</span></a></li>
            <li><a class="links-menu" href="/cadastrar-produtos.php">Cadastre-se</a></li>
            <li><a class="links-menu" href="/logar.php"><span class="material-icons">logout</span></a></li>
        </ul>
    </div>
</section>

<style>

    html,
    body {
        margin: auto;
        font-family: 'Roboto', sans-serif;

    }
    .header-section {
        position: relative;
        display: flex;
        justify-content: space-around;
        width: 100%;
        height: 100px;
        align-items: center;

        color: white;
        background: #EED9A3;
    }

    ul, li {
        margin: auto;
        display: flex;
    }

    li {
        margin-left: 20px;
    }


    li>a {
        text-decoration: none;
        color: inherit;
    }
    li>a:hover {
        color:burlywood;
    }
    .div-header {
        display: flex;
        width: 50%;
        justify-content: center;
    }
</style>



