<?php $titulo = 'Dashboard' ?>
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
<head>
    <meta charset=UTF-8>
    <meta name="viewport" content="width=device-width">
    <link rel="icon"  href="../img/logo.jpg" type="image/x-icon">
    <title><?php echo $titulo ?></title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<header>

    <section class="header-section">
        <div class="header-div">
            <a class="link-home" href="/home">
                <img src="../img/logo.jpg" width="60" height="60" style="border-radius: 50px" alt="logo">
            </a>
        </div>
        <div class="header-div">
            <form method="GET" class="header-input">
                <input name="pesquisa" id="pesquisa" type="search" placeholder="pesquisar">
                <button class="button-header"><span class="material-icons">search</span></button>
            </form>
        </div>
        <div class="header-div">
            <ul>
                <li><a href="/home"><span class="material-icons">home</span></a></li>
                <li><a href="/cadastrar-produtos">Cadastre-se</a></li>
                <li><a href="/logar"><span class="material-icons">login</span></a></li>
            </ul>
        </div>
    </section>

</header>
<style>

    html,
    body {
        margin: auto;
        font-family: 'Roboto', sans-serif;
    }

    .link-home {
        text-decoration: none;
        color: inherit;
    }

    .header-section {
        position: fixed;
        display: flex;
        justify-content: space-around;
        width: 100%;
        height: 100px;


        background-image: linear-gradient(#EED9A3, rgba(255, 255, 255, 0.45));
        color: #444444;


        margin-top: -10rem;
        margin-bottom: 2rem;
    }

    .header-div {
        display: flex;
        align-items: center;
        width: 33%;
        justify-content: center;
    }

    ul, li {
        margin: auto;
        display: flex;
    }

    li {
        margin-left: 20px;
    }

    input {
        width: 300px;
        border: none;
        padding: 5px;

        text-align: center;

        height: 40px;
        border-radius: 30px;
        background: white;

    }

    .button-header {
        color: white;

        background: burlywood !important;

        border: none;

        box-shadow: -5px 5px 20px rgba(0, 0, 0, 0.29);

        width: 15% !important;
    }

    .header-input, .button-header {
        width: 350px;
        height: 40px;
        display: flex;
        justify-content: center;
        align-items: center;

        border-radius: 30px;

        background: white;
    }

    li > a {
        text-decoration: none;
        color: inherit;
    }

    li > a:hover {
        color: burlywood;
    }
</style>