<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
<head>
    <meta charset=UTF-8>
    <meta name="viewport" content="width=device-width">
    <link rel="icon"  href="../img/logo.jpg" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</head>
<body>

<header>
    <section class="header-section">
        <div class="div-header"><a class="link-home" href="/home"><img src="../img/logo.jpg" alt="lgo" width="60"
                                                                       style="border-radius: 50px" height="60"></a>
        </div>
        <div class="div-header">
            <ul>
                <li><a class="links-menu" href="/home"><span class="material-icons">home</span></a></li>
                <li><a class="links-menu" href="/cadastrar-produtos">Cadastre-se</a></li>
                <li><a class="links-menu" href="/excluir-produto">Excluir</a></li>
                <div class="dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        Editar
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li class="dropdown-item"><a href="/banner">Banner</a></li>
                        <li class="dropdown-item"><a href="/super-promocao">Super Promoção</a></li>
                        <li class="dropdown-item"><a href="/produtos">Produtos</a></li>
                    </ul>
                </div>
                <li><a class="links-menu" href="/sair"><span class="material-icons">logout</span></a></li>
            </ul>
        </div>
    </section>
</header>
<style>

    html,
    body {
        margin: auto;
        font-family: 'Roboto', sans-serif;

    }

    .header-section {
        font-family: 'Roboto', sans-serif;
        position: relative;
        display: flex;
        justify-content: space-around;
        width: 100%;
        height: 100px;
        align-items: center;

        color: #363636;
        background-image: linear-gradient(rgb(241, 224, 182), rgb(255, 255, 255));
    }

    ul, li {
        margin: auto;
        display: flex;
    }

    li {
        margin-left: 20px;
    }


    li > a {
        text-decoration: none;
        color: inherit;
    }

    li > a:hover {
        color: burlywood;
    }

    .div-header {
        display: flex;
        width: 50%;
        justify-content: center;
    }

    .link-home {
        text-decoration: none;
        color: inherit;
    }
    .dropdown {
        margin: auto 15px;
    }
</style>



