<section class="principal">
    <h2 class="titulo-principal">Cadastrar administrador</h2>
</section>
<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-inicio" role="tabpanel" aria-labelledby="nav-inicio-tab">
        <section class="principal">
            <div class="cadastrar-formulario">
                <div class="div-cadastra">
                    <section class="section-cadastrar">
                        <form action="/realiza-cadastro-administrador" method="POST" enctype="multipart/form-data">
                            <div class="cad-card">
                                <div class="cadastro-um" id="cadastro-um">
                                    <div class="div-nome">
                                        <label for="nome" class="div-label">nome</label>
                                        <input type="text" name="nome" class="nome-cad"
                                               placeholder="digite seu nome" required>
                                    </div>
                                    <div class="div-nome">
                                        <label for="nome" class="div-label">Usuário</label>
                                        <input type="text" name="usuario" class="nome-cad"
                                               placeholder="Usuário do sistema" required>
                                    </div>
                                </div>
                            </div>
                    </section>
                </div>
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">

                        <button class="button-cadastro" id="nav-preco-tab" data-bs-toggle="tab"
                                data-bs-target="#nav-preco"
                                type="button" role="tab" aria-controls="nav-preco" aria-selected="false">PRÓXIMO
                        </button>

                    </div>
                </nav>

            </div>
        </section>
        <div class="progress barra-progresso">
            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                 style="width: 10%;" aria-valuenow="25" aria-valuemin="0"
                 aria-valuemax="100">Inicie o cadastro!
            </div>
        </div>
    </div>

    <div class="tab-pane fade" id="nav-preco" role="tabpanel" aria-labelledby="nav-preco-tab">
        <section class="principal">
            <div class="cadastrar-formulario">
                <section class="section-cadastrar">
                    <div class="div-nome">
                        <label class="div-label" for="preco">Email</label>
                        <input type="email" name="email" class="nome-cad" placeholder="seuemail@gmail.com" required>
                    </div>
                    <div class="div-nome">
                        <label class="div-label" for="preco">Senha</label>
                        <input type="password" name="senha" class="nome-cad" placeholder="*******" required>
                    </div>
                </section>
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">

                        <button class="button-cadastro" >Concluir
                        </button>

                    </div>
                </nav>
            </div>
        </section>
        <div class="progress barra-progresso">
            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                 style="width: 40%;" aria-valuenow="25" aria-valuemin="0"
                 aria-valuemax="100">80
            </div>
        </div>
    </div>

    </form>
    </section>
</div>
</div>

<style>body {background: #949494 !important;}</style>

