<section class="section-cadastrar" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <div class="div-cadastra">
        <form action="" method="POST" enctype="multipart/form-data" class="cadastrar-formulario">
        <h1 class="cadastro-cliente">Cadastre-se</h1>
            <div class="div-nome">
                <label for="nome" class="div-label">nome</label>
                <input type="text" name="nome" class="nome-cad" required placeholder="Digíte seu nome e sobrenome">
            </div>
            <div class="div-nome">
                <label class="div-label" for="email">email</label>
                <input class="nome-cad text" type="email" name="email" placeholder="seuemail@gmail.com" required>
            </div>
            <div class="div-nome">
                <label class="div-label" for="celular">celular</label>
                <input type="text" name="celular" class="nome-cad" placeholder="( ## ) ##### - ####" required>
            </div>
            <div class="div-nome">
                <label class="div-label" for="senha">senha</label>
                <input type="password" name="senha" class="nome-cad" placeholder="Digite sua senha" required>
                <small>*Senha maior que 6 caracteres</small>
            </div>
            <div class="div-nome">
                <label for='imagem' class="div-label">Foto do perfil</label>
                <input type="file" name="imagem" class="nome-cad">
            </div>
            <button class="button-cadastro">Cadastrar</button>
        </form>
    </div>
</section>
<style>body {background: #949494}</style>