<section class="section-produto">
    <div class="div-produto">
        <div class="formulario-produto">
            <form action="" method="post" class="finalizar-compra">
                <div for="" class="div-produtos">Quantitade  </div>
                    <select name="tipo-pagamento" id="pagamento">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>

                <div class="div-produtos" for="">Tipo de pagamento  </div>
                    <select name="tipo-pagamento" id="pagamento">
                        <option value="sem/pagamento">Escolha um tipo de pagamento</option>
                        <option value="pix">Pix</option>
                        <option value="boleta">Boleto</option>
                    </select>

            </form>
        </div>
    </div>
</section>

<style>
    .section-produto {
        width: 50%;
        display: flex;
        padding-top: 1rem;
        padding-left: 1rem;

        color: #444444;
    }
    .div-produto {
        margin: auto;
    }

    .input-compra {
        border: 1px solid rgba(0, 0, 0, 0.26);
    }
    .div-produtos {
        display: flex;
        margin-bottom: 5px;
        margin-top: 20px;
    }
</style>