<?php

use src\doctrine\infra\MysqlConnect;

require_once __DIR__ . './../header/header-adm.phtml'; ?>
<section class="lista-produtos">
    <h1 class="h1-titulos">Painel Administrativo</h1>
    <div class="lista">
        <table class="table">
            <div class="btn-pesquisa">
                <a href="/cadastrar-produtos">
                    <button class="btn-editar btn-mais">novo produto +</button>
                </a>
                <div class="header-div">
                    <form method="GET" class="header-input">
                        <input name="pesquisa" id="pesquisa" type="search" placeholder="pesquisar">
                        <div class="pesquisa-avancada">
                            <select class="form-select form-select-sm" name="categoria" aria-label=".form-select-sm example">
                                <option selected>categorias</option>
                                <option value="acessorio">Acessório</option>
                                <option value="bicicleta">Bicicleta</option>
                                <option value="celulares">celulares</option>
                                <option value="eletronicos">eletronicos</option>
                                <option value="carinho">Carrinho</option>
                                <option value="cama">cama</option>
                                <option value="sofa">sofa</option>
                                <option value="quarto">quarto</option>
                                <option value="banheiro">banheiro</option>
                                <option value="cozinha">cozinha</option>
                                <option value="vestuario">vestuário</option>
                            </select>
                        </div>
                        <button class="button-header"><span class="material-icons">search</span></button>
                    </form>
                </div>

            </div>
            <thead>
            <tr>
                <th id="id_prod" scope="col">id</th>
                <th id="nome_prod" scope="col">nome</th>
                <th id="descricao_prod" scope="col">descrição</th>
                <th id="preco_prod" scope="col">preço</th>
                <th id="categoria_prod" scope="col">Categoria</th>
            </tr>
            </thead>
            <tbody>
            <?php

            $this->mysql = (new MysqlConnect())->conect();


            $buscar = filter_input(
                INPUT_GET,
                'pesquisa',
                FILTER_SANITIZE_STRING
            );

            $nomecategoria = filter_input(
                INPUT_GET,
                'categoria',
                FILTER_SANITIZE_STRING
            );

            $dqlpadrao = "SELECT * FROM produtos";

            $mysql = "SELECT * FROM produtos 
            where `nome` LIKE '%$buscar%' 
            or `descricao` LIKE '%$buscar%'
            or `titulo_produto` LIKE '%$buscar%'
            or `categoria` LIKE '%$nomecategoria%'
            or `subcategoria` LIKE '%$nomecategoria%'";


            if ($buscar == 'undefined'
                || $buscar == ''
                || $nomecategoria == 'undefined'
                || $nomecategoria == ''
            ) {
                $produto = mysqli_query($this->mysql, $dqlpadrao);
            } else {
                $produto = mysqli_query($this->mysql, $mysql);
            }

            if (($produto) and ($produto->num_rows != 0)):

                while ($rows = mysqli_fetch_object($produto)): ?>

                    <tr>
                        <th scope="row"><?= $rows->id ?></th>
                        <td id="nome_prod"><?= $rows->nome ?></td>
                        <td id="descricao_prod"><?= $rows->descricao ?></td>
                        <td id="preco_prod">R$<?= $rows->preco ?></td>
                        <td id="categoria_prod"><?= $rows->categoria ?></td>
                        <div class="btn-ed-exc">
                            <td id="btn-editar-prod"><a href="/editar-produto?id=<?= $rows->id ?>">
                                    <button class="btn-editar">Editar</button>
                                </a></td>
                            <td id="btn-excluir-prod"><a href="/exluir-produto?id=<?= $rows->id ?>">
                                    <button class="btn-excluir">Excluir</button>
                                </a></td>
                        </div>
                    </tr>
                <?php endwhile; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</section>
