<section class="contato-newsletter">
    <form method="post" action="/salvar-newsletters" onblur="validateEmailAddress()" class="footer-contato-newsletters" enctype="multipart/form-data">
        <h2 class="footer-sub-contato-news">receber newsletter</h2>
        <div class="input-enviar">
            <input type="email" class="input-newsletter" id="email"  name="newsletter" placeholder="Digíte seu email aqui">
            <button class="newsletter-btn" id="validate">Enviar</button>
        </div>
        <div class="alert alert-danger" id="result" role="alert"></div>
    </form>
</section>

