<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
</script>

<?php

?>
<section class="section-campo">
    <table class="table">
        <thead class="thead-titulo">
        <p class="titulo-dados">DADOS DO PRODUTO</p>

        </thead>
        <div class="div-tabela">
            <tbody>
            <tr>
                <th scope="row">Nome</th>
                <td><?php echo $nome?></td>
            </tr>
            <tr>
                <th scope="row">Descrição</th>
                <td><?php echo $descricao?></td>
            </tr>
            <tr>
                <th scope="row">Preço</th>
                <td><?php echo $preco?></td>
            </tr>
            <tr>
                <th scope="row">Titulo do produto</th>
                <td> <?php echo $titulo?></td>

            </tr>
            <tr>
                <th scope="row">Desconto</th>
                <td><?php  echo $desc?></td>
            </tr>
            <tr>
                <th scope="row"> Categoria</th>
                <td><?php echo $categoria?></td>

            </tr>
            <tr>
                <th scope="row"> Sub-Categoria</th>
                <td><?php echo $subcat?></td>

            </tr>
            <tr>
                <th scope="row"> Marca</th>
                <td><?php echo $marcas?></td>

            </tr>
            <tr>
                <th scope="row">Imagem</th>
                <td><?php echo $caminho = 'arquivos/'.$nome.'.jpg'?></td>
            </tr>
            </tbody>
    </table>
    </div>
</section>
<style>
    .section-campo {
        width: 70%;
        margin: auto;

    }

    .table {
        width: 80% !important;
        margin: auto;
        background: #FFFFFF;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }

    thead {
        display: flex;
        justify-content: center;

    }

    .titulo-dados {
        width: 83%;
        text-align: center;
        margin: auto;
        font-weight: 700;
        color: #6A6A6A;
        font-size: 24px;
        background: #FAE09D;

        padding: 15px 0;

        border-radius: 15px;
    }

    .thead-titulo {
        width: 100%;
        justify-content: center;
        margin: auto;
    }

    .table > :not(:first-child) {
        border-top: none;
    }

    tbody, td, tfoot, th, thead, tr {
        border-color: inherit;
        border-style: none;
        border-width: 0;
    }

    th {
        width: 25%;
        text-align: center;
        border-right: 1px solid rgba(106, 106, 106, 0.18);
    }

    td {
        padding-left: 100px !important;
    }

    .table > :not(caption) > * > * {
        margin: 15px 25px !important;
    }

</style>