<section class="card-section">
    <div class="card">
        <img  class="imagem-produto" src="../public/img/images.jpg" alt="carrinho">
        <h2 class="titulo-produto">CARRINHO AUTO 2.0</h2>
        <div class="preco">Preço $<div class="valor">259,59</div>
        </div>
        <button class="button-produto">Comprar</button>
    </div>
    <div class="card">
        <img  class="imagem-produto" src="./../public/img/images.jpg" alt="carrinho">
        <h2 class="titulo-produto">CARRINHO AUTO 2.0</h2>
        <div class="preco">Preço $<div class="valor">259,59</div>
        </div>
        <button class="button-produto">Comprar</button>
    </div>
    <div class="card">
        <img  class="imagem-produto" src="./../public/img/images.jpg" alt="carrinho">
        <h2 class="titulo-produto">CARRINHO AUTO 2.0</h2>
        <div class="preco">Preço $<div class="valor">259,59</div>
        </div>
        <button class="button-produto">Comprar</button>
    </div>
    <div class="card">
        <img  class="imagem-produto" src="./../public/img/images.jpg" alt="carrinho">
        <h2 class="titulo-produto">CARRINHO AUTO 2.0</h2>
        <div class="preco">Preço $<div class="valor">259,59</div>
        </div>
        <button class="button-produto">Comprar</button>
    </div>
</section>

<style>
    .card-section {
        display: flex;
        flex-direction: row;
        margin: auto;
        width: 75%;

        margin-top: 1rem;
        margin-left: 2.5rem;
    }
    .card {
        display: flex;
        flex-direction: column;
        padding-left: 3rem;

        width: 202px;
        height: 323px;
    }
    .imagem-produto {
        width: 202px;
        height: 199px;



        box-shadow: 0 3px 10px rgba(0, 0, 0, 0.25);
    }
    .titulo-produto {
        margin: auto;

        color: #444;
        font-size: 18px;
        font-family: 'Roboto', sans-serif;

        font-weight: 500;
    }

    .preco, .valor {
        font-family: 'Roboto', sans-serif;
        margin: auto;
        width: auto;

    }
    .preco {
        color: #000;
    }
    .valor {
        color: #6a6a6a;
    }

    .button-produto {
        width: 146px !important;
        height: 29px !important;

        border-radius: 12px !important;

        margin-top: 10px;

        color: white !important;
        background: #6a6a6a !important;

        font-size: 18px;
        font-family: 'Roboto', sans-serif;
        text-transform: uppercase;

        border: none;
    }

    .button-produto:hover {
        transition: 0.8s;
        background: bisque !important;
    }

</style>