<section class="footer-base">
    <div class="parte-cima">
        <div class="conteudo-links">
            <h4 class="footer-sub-titulo">Categorias e Subs</h4>
            <ul class="footer-ul">
                <li class="footer-li">acessórios</li>
                <li class="footer-li">bicicletas</li>
                <li class="footer-li">Eletrodoméstico</li>
                <li class="footer-li">Móveis</li>
            </ul>
        </div>
    </div>
    <div class="parte-baixo">

    </div>
</section>

<style>

</style>